Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
== RESTART: E:\00.笔记\ob\Obsidian-PythonScript-0.06\bilibili_to_ob.py =
{'code': 0,
 'data': {'aid': 633056059,
          'bvid': 'BV1wb4y1m7rZ',
          'cid': 412044734,
          'copyright': 1,
          'ctime': 1632202259,
          'desc': '练后拉伸：BV1fq4y1M7L1\n'
                  '除了体能，跑步怎么练：BV1PT4y1G7Nt\n'
                  '\n'
                  '其他体测视频：https://www.bilibili.com/medialist/play/ml941838362',
          'desc_v2': [{'biz_id': 0,
                       'raw_text': '练后拉伸：BV1fq4y1M7L1\n'
                                   '除了体能，跑步怎么练：BV1PT4y1G7Nt\n'
                                   '\n'
                                   '其他体测视频：https://www.bilibili.com/medialist/play/ml941838362',
                       'type': 1}],
          'dimension': {'height': 1080, 'rotate': 0, 'width': 1920},
          'duration': 562,
          'dynamic': '跟练版来了！\n练3天给你一个不一样的身体！\n练7天跑步脚下生风！',
          'honor_reply': {'honor': [{'aid': 633056059,
                                     'desc': '热门',
                                     'type': 4,
                                     'weekly_recommend_num': 0}]},
          'is_chargeable_season': False,
          'is_season_display': True,
          'is_story': False,
          'like_icon': '',
          'mission_id': 142749,
          'no_cache': False,
          'owner': {'face': 'https://i1.hdslb.com/bfs/face/7578096a896bd0c13db75984668c0a4d7f2a7253.jpg',
                    'mid': 451645162,
                    'name': '跑步的子章老师'},
          'pages': [{'cid': 412044734,
                     'dimension': {'height': 1080, 'rotate': 0, 'width': 1920},
                     'duration': 562,
                     'first_frame': 'http://i1.hdslb.com/bfs/storyff/n210921a22j9hvavapy0gu38htwsjw4k_firsti.jpg',
                     'from': 'vupload',
                     'page': 1,
                     'part': '体差生跟练计划',
                     'vid': '',
                     'weblink': ''}],
          'pic': 'http://i2.hdslb.com/bfs/archive/0e4744171dfb649ad42034ade37f86b4f75e7204.jpg',
          'premiere': None,
          'pubdate': 1632202259,
          'rights': {'arc_pay': 0,
                     'autoplay': 1,
                     'bp': 0,
                     'clean_mode': 0,
                     'download': 1,
                     'elec': 0,
                     'free_watch': 0,
                     'hd5': 1,
                     'is_360': 0,
                     'is_cooperation': 0,
                     'is_stein_gate': 0,
                     'movie': 0,
                     'no_background': 0,
                     'no_reprint': 1,
                     'no_share': 0,
                     'pay': 0,
                     'ugc_pay': 0,
                     'ugc_pay_preview': 0},
          'season_id': 501337,
          'stat': {'aid': 633056059,
                   'argue_msg': '',
                   'coin': 53135,
                   'danmaku': 4859,
                   'dislike': 0,
                   'evaluation': '',
                   'favorite': 145316,
                   'his_rank': 0,
                   'like': 95938,
                   'now_rank': 0,
                   'reply': 3530,
                   'share': 10462,
                   'view': 1429403},
          'state': 0,
          'subtitle': {'allow_submit': True,
                       'list': [{'ai_status': 0,
                                 'ai_type': 0,
                                 'author': {'birthday': 0,
                                            'face': '',
                                            'in_reg_audit': 0,
                                            'is_deleted': 0,
                                            'is_fake_account': 0,
                                            'is_senior_member': 0,
                                            'mid': 0,
                                            'name': '',
                                            'rank': 0,
                                            'sex': '',
                                            'sign': ''},
                                 'id': 49321610709712896,
                                 'id_str': '49321610709712896',
                                 'is_lock': False,
                                 'lan': 'zh-CN',
                                 'lan_doc': '中文（中国）',
                                 'subtitle_url': 'http://i0.hdslb.com/bfs/subtitle/a5f5118b379cc036c5928f930c4ed604a00304ec.json',
                                 'type': 0},
                                {'ai_status': 2,
                                 'ai_type': 0,
                                 'author': {'birthday': 0,
                                            'face': '',
                                            'in_reg_audit': 0,
                                            'is_deleted': 0,
                                            'is_fake_account': 0,
                                            'is_senior_member': 0,
                                            'mid': 0,
                                            'name': '',
                                            'rank': 0,
                                            'sex': '',
                                            'sign': ''},
                                 'id': 1066546959957071360,
                                 'id_str': '1066546959957071360',
                                 'is_lock': False,
                                 'lan': 'ai-zh',
                                 'lan_doc': '中文（自动生成）',
                                 'subtitle_url': 'http://i0.hdslb.com/bfs/ai_subtitle/prod/63305605941204473400ba7b24477e4217f487be4ecd1b0d5e',
                                 'type': 1}]},
          'teenage_mode': 0,
          'tid': 164,
          'title': '【拯救体差生】在家就能练的「体能提升」训练｜轻松体测不痛苦（完整跟练版）',
          'tname': '健身',
          'ugc_season': {'attribute': 140,
                         'cover': 'https://archive.biliimg.com/bfs/archive/ba14e08b13149e13d2a534850a3d0d04a179ac0a.jpg',
                         'ep_count': 4,
                         'id': 501337,
                         'intro': '',
                         'is_pay_season': False,
                         'mid': 451645162,
                         'season_type': 1,
                         'sections': [{'episodes': [
                                                    {'aid': 633056059,
                                                     'arc': {'aid': 633056059,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1632202259,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 562,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/0e4744171dfb649ad42034ade37f86b4f75e7204.jpg',
                                                             'pubdate': 1632202259,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 633056059,
                                                                      'argue_msg': '',
                                                                      'coin': 53135,
                                                                      'danmaku': 4859,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 145316,
                                                                      'his_rank': 0,
                                                                      'like': 95938,
                                                                      'now_rank': 0,
                                                                      'reply': 3530,
                                                                      'share': 10462,
                                                                      'view': 1429403},
                                                             'state': 0,
                                                             'title': '居家「体测提升」训练',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1wb4y1m7rZ',
                                                     'cid': 412044734,
                                                     'id': 7319344,
                                                     'page': {'cid': 412044734,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 562,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '体差生跟练计划',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 501337,
                                                     'section_id': 579737,
                                                     'title': '居家「体测提升」训练'},
                                                    {'aid': 766000474,
                                                     'arc': {'aid': 766000474,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1643438624,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 400,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/31be1357d7615f07c31561f4e11ca7b0710bb4e7.jpg',
                                                             'pubdate': 1643438624,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 766000474,
                                                                      'argue_msg': '',
                                                                      'coin': 23899,
                                                                      'danmaku': 2089,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 53710,
                                                                      'his_rank': 0,
                                                                      'like': 29757,
                                                                      'now_rank': 0,
                                                                      'reply': 397,
                                                                      'share': 4472,
                                                                      'view': 392901},
                                                             'state': 0,
                                                             'title': '5分钟肩颈拉伸',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1Wr4y1a7me',
                                                     'cid': 496381475,
                                                     'id': 7319405,
                                                     'page': {'cid': 496381475,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 400,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '颈椎活动操',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 501337,
                                                     'section_id': 579737,
                                                     'title': '5分钟肩颈拉伸'},
                                                    {'aid': 886146555,
                                                     'arc': {'aid': 886146555,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1610452732,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 926,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/a25166ad079ec49223cff3138b02543c6a087498.jpg',
                                                             'pubdate': 1610452732,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 886146555,
                                                                      'argue_msg': '',
                                                                      'coin': 7333,
                                                                      'danmaku': 2318,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 19426,
                                                                      'his_rank': 0,
                                                                      'like': 14223,
                                                                      'now_rank': 0,
                                                                      'reply': 703,
                                                                      'share': 1494,
                                                                      'view': 358798},
                                                             'state': 0,
                                                             'title': '零基础俯卧撑训练',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV14K4y1W7iQ',
                                                     'cid': 281544390,
                                                     'id': 7319433,
                                                     'page': {'cid': 281544390,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 926,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '100个俯卧撑（带字幕）',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 501337,
                                                     'section_id': 579737,
                                                     'title': '零基础俯卧撑训练'},
                                                    {'aid': 756631967,
                                                     'arc': {'aid': 756631967,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1613368805,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 1746,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/6a0bc928b36678674624ebc3cdc082f5255e46e5.jpg',
                                                             'pubdate': 1613368805,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 756631967,
                                                                      'argue_msg': '',
                                                                      'coin': 4411,
                                                                      'danmaku': 338,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 13875,
                                                                      'his_rank': 0,
                                                                      'like': 7664,
                                                                      'now_rank': 0,
                                                                      'reply': 459,
                                                                      'share': 1133,
                                                                      'view': 156742},
                                                             'state': 0,
                                                             'title': '零基础逆袭弹跳',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1Cr4y1P7hj',
                                                     'cid': 297796345,
                                                     'id': 7319458,
                                                     'page': {'cid': 297796345,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 1746,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '完整弹跳跟练',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 501337,
                                                     'section_id': 579737,
                                                     'title': '零基础逆袭弹跳'}],
                                       'id': 579737,
                                       'season_id': 501337,
                                       'title': '正片',
                                       'type': 1}],
                         'sign_state': 0,
                         'stat': {'coin': 88778,
                                  'danmaku': 9604,
                                  'fav': 232327,
                                  'his_rank': 0,
                                  'like': 147581,
                                  'now_rank': 0,
                                  'reply': 5089,
                                  'season_id': 501337,
                                  'share': 17561,
                                  'view': 2337836},
                         'title': '14天体能逆袭打卡挑战'},
          'user_garb': {'url_image_ani_cut': ''},
          'videos': 1},
 'message': '0',
 'ttl': 1}
33333 14天体能逆袭打卡挑战
{'code': 0,
 'data': {'aid': 933563283,
          'bvid': 'BV17T4y1o7mj',
          'cid': 424908014,
          'copyright': 1,
          'ctime': 1634198452,
          'desc': '做俯卧撑的时候总感觉手臂没力气，撑不住 or 动作只能做一半，稍微下深一点就扑地上 or  '
                  '别人练完都是胸酸胳膊酸，你却腰酸到不行 or '
                  '习惯性的把胳膊肘打的很开，甚至还要往前拐一下才能退起身体。如果你也有这些问题，甚至连一个俯卧撑也做不了，那看完这期视频，跟着我教你的5个步骤练习，就能快速解锁俯卧撑！这里是#Erik的海盗电台#，Let‘s '
                  'ROCK！谢谢大家观看，喜欢我内容的话不妨点赞投币收藏，还有关注，您的鼓励是我最大的动力！ B站：Erik埃里克 '
                  '答疑微信：bufferik',
          'desc_v2': [{'biz_id': 0,
                       'raw_text': '做俯卧撑的时候总感觉手臂没力气，撑不住 or 动作只能做一半，稍微下深一点就扑地上 '
                                   'or  别人练完都是胸酸胳膊酸，你却腰酸到不行 or '
                                   '习惯性的把胳膊肘打的很开，甚至还要往前拐一下才能退起身体。如果你也有这些问题，甚至连一个俯卧撑也做不了，那看完这期视频，跟着我教你的5个步骤练习，就能快速解锁俯卧撑！这里是#Erik的海盗电台#，Let‘s '
                                   'ROCK！谢谢大家观看，喜欢我内容的话不妨点赞投币收藏，还有关注，您的鼓励是我最大的动力！ '
                                   'B站：Erik埃里克 答疑微信：bufferik',
                       'type': 1}],
          'dimension': {'height': 1080, 'rotate': 0, 'width': 1920},
          'duration': 369,
          'dynamic': '',
          'honor_reply': {'honor': [{'aid': 933563283,
                                     'desc': '热门',
                                     'type': 4,
                                     'weekly_recommend_num': 0}]},
          'is_chargeable_season': False,
          'is_season_display': True,
          'is_story': False,
          'like_icon': '',
          'mission_id': 142747,
          'no_cache': False,
          'owner': {'face': 'https://i2.hdslb.com/bfs/face/c4dfa72f2d33d18df098bb19bb4c369e9f0de35e.jpg',
                    'mid': 23640791,
                    'name': 'Erik埃里克'},
          'pages': [{'cid': 424908014,
                     'dimension': {'height': 1080, 'rotate': 0, 'width': 1920},
                     'duration': 369,
                     'first_frame': 'http://i1.hdslb.com/bfs/storyff/n211014a23uh9cmwy10onuwmzpbg3pea_firsti.jpg',
                     'from': 'vupload',
                     'page': 1,
                     'part': '俯卧撑',
                     'vid': '',
                     'weblink': ''}],
          'pic': 'http://i1.hdslb.com/bfs/archive/3b76bf476c50429579fb92a5c1fe48a19db26ffa.jpg',
          'premiere': None,
          'pubdate': 1634198452,
          'rights': {'arc_pay': 0,
                     'autoplay': 1,
                     'bp': 0,
                     'clean_mode': 0,
                     'download': 1,
                     'elec': 0,
                     'free_watch': 0,
                     'hd5': 1,
                     'is_360': 0,
                     'is_cooperation': 0,
                     'is_stein_gate': 0,
                     'movie': 0,
                     'no_background': 0,
                     'no_reprint': 1,
                     'no_share': 0,
                     'pay': 0,
                     'ugc_pay': 0,
                     'ugc_pay_preview': 0},
          'season_id': 499050,
          'stat': {'aid': 933563283,
                   'argue_msg': '',
                   'coin': 58435,
                   'danmaku': 1800,
                   'dislike': 0,
                   'evaluation': '',
                   'favorite': 159039,
                   'his_rank': 0,
                   'like': 85030,
                   'now_rank': 0,
                   'reply': 1327,
                   'share': 8832,
                   'view': 1937960},
          'state': 0,
          'subtitle': {'allow_submit': False,
                       'list': [{'ai_status': 2,
                                 'ai_type': 0,
                                 'author': {'birthday': 0,
                                            'face': '',
                                            'in_reg_audit': 0,
                                            'is_deleted': 0,
                                            'is_fake_account': 0,
                                            'is_senior_member': 0,
                                            'mid': 0,
                                            'name': '',
                                            'rank': 0,
                                            'sex': '',
                                            'sign': ''},
                                 'id': 1058933709215934976,
                                 'id_str': '1058933709215934976',
                                 'is_lock': False,
                                 'lan': 'ai-zh',
                                 'lan_doc': '中文（自动生成）',
                                 'subtitle_url': 'http://i0.hdslb.com/bfs/ai_subtitle/prod/93356328342490801416e76e2495e868cd235d60db33889ad0',
                                 'type': 1}]},
          'teenage_mode': 0,
          'tid': 164,
          'title': '最详细俯卧撑解锁教程，5个步骤，提高俯卧撑数量和动作质量',
          'tname': '健身',
          'ugc_season': {'attribute': 140,
                         'cover': 'https://archive.biliimg.com/bfs/archive/58381e2aeea07e1b676efa5fb0264202b4840053.jpg',
                         'ep_count': 10,
                         'id': 499050,
                         'intro': '',
                         'is_pay_season': False,
                         'mid': 23640791,
                         'season_type': 1,
                         'sections': [{'episodes': [{'aid': 933563283,
                                                     'arc': {'aid': 933563283,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1634198452,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 369,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i1.hdslb.com/bfs/archive/3b76bf476c50429579fb92a5c1fe48a19db26ffa.jpg',
                                                             'pubdate': 1634198452,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 933563283,
                                                                      'argue_msg': '',
                                                                      'coin': 58435,
                                                                      'danmaku': 1800,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 159039,
                                                                      'his_rank': 0,
                                                                      'like': 85030,
                                                                      'now_rank': 0,
                                                                      'reply': 1327,
                                                                      'share': 8832,
                                                                      'view': 1937960},
                                                             'state': 0,
                                                             'title': '解锁俯卧撑',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV17T4y1o7mj',
                                                     'cid': 424908014,
                                                     'id': 7271613,
                                                     'page': {'cid': 424908014,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 369,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '俯卧撑',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '解锁俯卧撑'},
                                                    {'aid': 679101550,
                                                     'arc': {'aid': 679101550,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1645086010,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 1044,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/0700baa6b2997b7a143c3b589d5e719b7bcc3637.jpg',
                                                             'pubdate': 1645086010,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 679101550,
                                                                      'argue_msg': '',
                                                                      'coin': 17395,
                                                                      'danmaku': 3515,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 56959,
                                                                      'his_rank': 0,
                                                                      'like': 23604,
                                                                      'now_rank': 0,
                                                                      'reply': 1134,
                                                                      'share': 7128,
                                                                      'view': 873168},
                                                             'state': 0,
                                                             'title': '【每天一次】最高效的跳绳减脂方法，强化核心不伤膝，新手友好',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV11m4y1d7xy',
                                                     'cid': 510927418,
                                                     'id': 7658091,
                                                     'page': {'cid': 510927418,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 1044,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '快速减脂',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '【每天一次】最高效的跳绳减脂方法，强化核心不伤膝，新手友好'},
                                                    {'aid': 937377588,
                                                     'arc': {'aid': 937377588,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1647862337,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 1189,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/0087638acbf19f46706cfbc02d58611411e27ea6.jpg',
                                                             'pubdate': 1647862337,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 937377588,
                                                                      'argue_msg': '',
                                                                      'coin': 12925,
                                                                      'danmaku': 4056,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 44301,
                                                                      'his_rank': 0,
                                                                      'like': 16229,
                                                                      'now_rank': 0,
                                                                      'reply': 436,
                                                                      'share': 4394,
                                                                      'view': 465303},
                                                             'state': 0,
                                                             'title': '弹力带全身训练',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1ZT4y1U7vX',
                                                     'cid': 555260368,
                                                     'id': 7271610,
                                                     'page': {'cid': 555260368,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 1189,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '弹力带训练',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '弹力带全身训练'},
                                                    {'aid': 506317872,
                                                     'arc': {'aid': 506317872,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1635235574,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 395,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i0.hdslb.com/bfs/archive/76896c1c25e2ea6bc0d83cd1aebbf132bbf59e28.jpg',
                                                             'pubdate': 1635235574,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 506317872,
                                                                      'argue_msg': '',
                                                                      'coin': 4668,
                                                                      'danmaku': 242,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 10521,
                                                                      'his_rank': 0,
                                                                      'like': 9917,
                                                                      'now_rank': 0,
                                                                      'reply': 229,
                                                                      'share': 429,
                                                                      'view': 441034},
                                                             'state': 0,
                                                             'title': '户外增肌训练',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV13u411o753',
                                                     'cid': 431227049,
                                                     'id': 7271612,
                                                     'page': {'cid': 431227049,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 395,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '校园增肌',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '户外增肌训练'},
                                                    {'aid': 976649512,
                                                     'arc': {'aid': 976649512,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1637136912,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 434,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i0.hdslb.com/bfs/archive/323d7613c6f9041cb560e9a6233f92bae27d0e80.jpg',
                                                             'pubdate': 1637136912,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 976649512,
                                                                      'argue_msg': '',
                                                                      'coin': 15294,
                                                                      'danmaku': 1305,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 42073,
                                                                      'his_rank': 0,
                                                                      'like': 28567,
                                                                      'now_rank': 0,
                                                                      'reply': 618,
                                                                      'share': 3118,
                                                                      'view': 977141},
                                                             'state': 0,
                                                             'title': '解锁引体向上',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1S44y1e7pL',
                                                     'cid': 444345151,
                                                     'id': 7271611,
                                                     'page': {'cid': 444345151,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 434,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '引体向上_',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '解锁引体向上'},
                                                    {'aid': 335893423,
                                                     'arc': {'aid': 335893423,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1633344983,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 499,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i1.hdslb.com/bfs/archive/8f44380e27d9a12b6525ae4d80c850c0e7e7cc9d.jpg',
                                                             'pubdate': 1633344983,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 335893423,
                                                                      'argue_msg': '',
                                                                      'coin': 3067,
                                                                      'danmaku': 442,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 9410,
                                                                      'his_rank': 0,
                                                                      'like': 6358,
                                                                      'now_rank': 0,
                                                                      'reply': 191,
                                                                      'share': 1071,
                                                                      'view': 169625},
                                                             'state': 0,
                                                             'title': '巧克力腹肌',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1qR4y1n7Lm',
                                                     'cid': 419473769,
                                                     'id': 7271614,
                                                     'page': {'cid': 419473769,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 499,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '腹肌',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '巧克力腹肌'},
                                                    {'aid': 334154586,
                                                     'arc': {'aid': 334154586,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1626329603,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 395,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/997bb60d2c092d84202028fe46ca097381e3ae8c.jpg',
                                                             'pubdate': 1626329603,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 334154586,
                                                                      'argue_msg': '',
                                                                      'coin': 6958,
                                                                      'danmaku': 556,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 20923,
                                                                      'his_rank': 0,
                                                                      'like': 13286,
                                                                      'now_rank': 0,
                                                                      'reply': 445,
                                                                      'share': 1054,
                                                                      'view': 385264},
                                                             'state': 0,
                                                             'title': '增加肩宽',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1xw411d7Y2',
                                                     'cid': 370244049,
                                                     'id': 7271615,
                                                     'page': {'cid': 370244049,
                                                              'dimension': {'height': 1080,
                                                                            'rotate': 0,
                                                                            'width': 1920},
                                                              'duration': 395,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '宽肩训练三角肌',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '增加肩宽'},
                                                    {'aid': 685388997,
                                                     'arc': {'aid': 685388997,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1656585960,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 1176,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i1.hdslb.com/bfs/archive/ea39e5aa9ff16410255ee96c4b6818138b86977b.jpg',
                                                             'pubdate': 1656585960,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 685388997,
                                                                      'argue_msg': '',
                                                                      'coin': 2731,
                                                                      'danmaku': 999,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 8891,
                                                                      'his_rank': 0,
                                                                      'like': 4218,
                                                                      'now_rank': 0,
                                                                      'reply': 181,
                                                                      'share': 683,
                                                                      'view': 126306},
                                                             'state': 0,
                                                             'title': '【打卡】15分钟跳绳+腰腹训练，高效刷脂减小腰围，音乐卡点',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1BU4y1Q7Z4',
                                                     'cid': 760051568,
                                                     'id': 7770256,
                                                     'page': {'cid': 760051568,
                                                              'dimension': {'height': 2160,
                                                                            'rotate': 0,
                                                                            'width': 3840},
                                                              'duration': 1176,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '15分钟高效跳绳燃脂，这样跳才能瘦的快',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '【打卡】15分钟跳绳+腰腹训练，高效刷脂减小腰围，音乐卡点'},
                                                    {'aid': 555990935,
                                                     'arc': {'aid': 555990935,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1657703253,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 657,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i2.hdslb.com/bfs/archive/e035bbc71c2838ec4a8e91d3b8d237c04e5bf7b8.jpg',
                                                             'pubdate': 1657703253,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 555990935,
                                                                      'argue_msg': '',
                                                                      'coin': 3137,
                                                                      'danmaku': 550,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 11665,
                                                                      'his_rank': 0,
                                                                      'like': 7029,
                                                                      'now_rank': 0,
                                                                      'reply': 301,
                                                                      'share': 444,
                                                                      'view': 152878},
                                                             'state': 0,
                                                             'title': '俯卧撑手腕痛 '
                                                                      'I 3步解决',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1Je4y1d7GM',
                                                     'cid': 772041952,
                                                     'id': 8393114,
                                                     'page': {'cid': 772041952,
                                                              'dimension': {'height': 2160,
                                                                            'rotate': 0,
                                                                            'width': 3840},
                                                              'duration': 657,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '俯卧撑手腕痛 '
                                                                      'I 3步解决',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '俯卧撑手腕痛 I 3步解决'},
                                                    {'aid': 602515704,
                                                     'arc': {'aid': 602515704,
                                                             'author': {'face': '',
                                                                        'mid': 0,
                                                                        'name': ''},
                                                             'copyright': 0,
                                                             'ctime': 1662025200,
                                                             'desc': '',
                                                             'desc_v2': None,
                                                             'dimension': {'height': 0,
                                                                           'rotate': 0,
                                                                           'width': 0},
                                                             'duration': 763,
                                                             'dynamic': '',
                                                             'is_blooper': False,
                                                             'is_chargeable_season': False,
                                                             'pic': 'http://i0.hdslb.com/bfs/archive/0eb0a508d1cb59817cd265ff0c4841921ab2d5d2.jpg',
                                                             'pubdate': 1662025200,
                                                             'rights': {'arc_pay': 0,
                                                                        'autoplay': 0,
                                                                        'bp': 0,
                                                                        'download': 0,
                                                                        'elec': 0,
                                                                        'free_watch': 0,
                                                                        'hd5': 0,
                                                                        'is_cooperation': 0,
                                                                        'movie': 0,
                                                                        'no_reprint': 0,
                                                                        'pay': 0,
                                                                        'ugc_pay': 0,
                                                                        'ugc_pay_preview': 0},
                                                             'stat': {'aid': 602515704,
                                                                      'argue_msg': '',
                                                                      'coin': 11290,
                                                                      'danmaku': 4088,
                                                                      'dislike': 0,
                                                                      'evaluation': '',
                                                                      'fav': 68779,
                                                                      'his_rank': 0,
                                                                      'like': 25548,
                                                                      'now_rank': 0,
                                                                      'reply': 574,
                                                                      'share': 2886,
                                                                      'view': 804025},
                                                             'state': 0,
                                                             'title': '练腹肌，有手就行 '
                                                                      '| '
                                                                      '10分钟腹肌撕裂，坚持就能拥有',
                                                             'type_id': 0,
                                                             'type_name': '',
                                                             'videos': 0},
                                                     'attribute': 0,
                                                     'bvid': 'BV1sB4y1G7q3',
                                                     'cid': 820898836,
                                                     'id': 11115606,
                                                     'page': {'cid': 820898836,
                                                              'dimension': {'height': 2160,
                                                                            'rotate': 0,
                                                                            'width': 3840},
                                                              'duration': 763,
                                                              'from': 'vupload',
                                                              'page': 1,
                                                              'part': '练腹肌，有手就行 '
                                                                      '| '
                                                                      '10分钟腹肌撕裂，坚持就能拥有',
                                                              'vid': '',
                                                              'weblink': ''},
                                                     'season_id': 499050,
                                                     'section_id': 577137,
                                                     'title': '练腹肌，有手就行 | '
                                                              '10分钟腹肌撕裂，坚持就能拥有'}],
                                       'id': 577137,
                                       'season_id': 499050,
                                       'title': '正片',
                                       'type': 1}],
                         'sign_state': 0,
                         'stat': {'coin': 135900,
                                  'danmaku': 17553,
                                  'fav': 432561,
                                  'his_rank': 0,
                                  'like': 219786,
                                  'now_rank': 0,
                                  'reply': 5436,
                                  'season_id': 499050,
                                  'share': 30039,
                                  'view': 6332694},
                         'title': '增肌增力，减脂瘦身'},
          'user_garb': {'url_image_ani_cut': ''},
          'videos': 1},
 'message': '0',
 'ttl': 1}
33333 增肌增力，减脂瘦身
>>> 